os: linux
dist: trusty

sudo: require

language: cpp

compiler:
  - clang
  - gcc

notifications:
  email: false


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test


before_install:
  - pip install --user cpp-coveralls
  - sudo apt-add-repository --yes ppa:beineri/opt-qt551-trusty && sudo apt-get update -qq && sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update -qq
  - git clone https://github.com/g-truc/glm && sudo cp -r glm/glm /usr/local/include && sudo apt-get install -qq g++-7 && sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  #- sudo apt-get install -y lcov
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.13.orig.tar.gz
  - tar xf lcov_1.13.orig.tar.gz
  - sudo make -C lcov-1.13/ install
  - gem install coveralls-lcov
  #- sudo apt-get install ggcov && sudo ln -sf /usr/bin/gcov-4.7 /usr/bin/gcov
  #- sudo ln -sf /usr/bin/gcov-4.9 /usr/bin/gcov

#install:
#
#  - git clone https://github.com/google/googletest && cd googletest && mkdir build && cd build && cmake -DBUILD_GMOCK=OFF .. && make -j2 && sudo make install

script:
  - cd /home/travis/build/Grigler/RB
  - cmake -H. -Bbuild
  - cd build
  - cmake --build .
  #- make check
  - ./bin/tests

after_success:
  - lcov --directory . --capture --output-file coverage.info --
  - lcov --remove coverage.info '/usr/include/*' '/home/travis/build/Grigler/RB/contrib/*' '/home/travis/build/Grigler/RB/src/example/*' '/home/travis/build/Grigler/RB/src/tests/*''.*/CMakeFiles/*' '/home/travis/build/Grigler/RB/build/*'
  - lcov --list coverage.info
  - coveralls-lcov coverage.info
  #- coveralls --root .. --verbose --gcov-options '\lpw' -e build/googletest -e contrib -e src/example -e src/tests -e build/CMakeFiles -e glm
  #- coveralls --root .. --verbose -e build/googletest -e contrib -e src/example -e src/tests -e build/CMakeFiles -e glm