os: linux
dist: trusty

sudo: require

language: cpp

compiler:
  - clang
  - gcc

notifications:
  email: false


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test


before_install:
  - pip install --user cpp-coveralls
  - sudo apt-add-repository --yes ppa:beineri/opt-qt551-trusty && sudo apt-get update -qq && sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update -qq
  - git clone https://github.com/g-truc/glm && sudo cp -r glm/glm /usr/local/include && sudo apt-get install -qq g++-7 && sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90

#install:
#
#  - git clone https://github.com/google/googletest && cd googletest && mkdir build && cd build && cmake -DBUILD_GMOCK=OFF .. && make -j2 && sudo make install

script:
  - cd /home/travis/build/Grigler/RB
  - cmake -H. -Bbuild
  - cd build
  - cmake --build .
  - ./bin/tests

after_success:
  - coveralls --build-root build --gcov-options '\lp' -e build/googletest -e contrib -e src/example
